import Head from "next/head";
import Image from "next/image";
import BlogCard from "../components/BlogCard";
import Button from "../components/Button";

const blogPosts = [
  {
    id: "1",
    title: "The important of learning CSS",
    image:
      "https://resizer.glanacion.com/resizer/BuTvjBzeTwoEFbwcn1mRuhu58Ak=/768x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/TYKUQAULKZCDZIFN2WCD2XXI3E.jpg",
    excerpt:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit numquam possimus quaerat aperiam odit reiciendis veniam sapiente placeat laborum! Quisquam aliquid illum eius rem cumque quas suscipit deleniti consequatur tempore?",
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10 max-w-screen-xl grid gap-8">
        {/* hERO*/}
        <div className={"flex flex-col md:flex-row items-center pr-8"}>
          {/* taglines */}
          <div className={"flex-1 mb-5"}>
            <p className={"text-xs text-secondary font-mono"}>
              {" "}
              Development | Code | Entrepreneurship
            </p>
            <h1 className="text-2xl my-3">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
            </h1>
            <p className="text-sm text-gray-300">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et
              deleniti maiores blanditiis illo nisi aspernatur, totam ea
              molestiae sint unde qui! Labore, cum? Dolorum perspiciatis
              reprehenderit dolorem modi asperiores deserunt?
            </p>
          </div>

          {/* video */}
          <div
            className={
              "flex-1 relative justify-center items-center mr-8 mb-10 w-full"
            }
          >
            <Image
              src="/images/profile.jpg"
              alt=""
              width={144}
              height={144}
              layout={"responsive"}
            />
            <div className="absolute bottom-0 right-0 w-20 transform translate-x-10 translate-y-9">
              <Image
                src="/images/pattern.png"
                alt=""
                width={1304}
                height={2106}
                layout={"responsive"}
              />
            </div>
          </div>
          {/* button */}
          <Button href="" text="Sign Up" />
        </div>
        {/* BLOG */}
        <section className="flex flex-col items-center">
          <h1 className="text-2xl">Blog</h1>
          <p className="text-xs text-gray-500 text-center">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto
            eum eligendi modi illum quas, unde aperiam corrupti sint dignissimos
            expedita minus suscipit, nobis voluptatum. Similique vitae iusto
            exercitationem doloribus velit?
          </p>
          {blogPosts.map((post) => (
            <BlogCard post={post} />
          ))}
        </section>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
